name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: ░▒▓█ # optional
          TIME_RANGE: last_7_days # optional
          CODE_LANG: rust
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: gitignore
